# Dockerfile.node
FROM node:20-alpine

WORKDIR /app

# Copy package.json and package-lock.json (if you have one)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code (this will include your React 'build' folder)
COPY . .

# Expose the port that the server will listen on
EXPOSE 3000

# Start the server
CMD ["node", "server.js"]